### ISSUE TITLE
为啥我感觉有问题啊

### ISSUE THREAD

**Issue by zyx0609** [liupengs/DES_Python#1]
将字符转化为二进制函数里面  
code_ord=int(key,16)  这句出错了 invalid literal for int() with base 16: 'I'
我有一个小疑惑~为什么要先把密钥转化为十六进制？有什么必要吗

**Comment by zyx0609** [comment]
还有，输入密钥时写着“长度不限”，实际上不是这个样子的啊

**Comment by zyx0609** [comment]
@liupengs   啊好想快点得到答复.......  sorry

**Comment by liupengs** [comment]
不好意思， 这代码还是我n年前学密码学的时候敲的代码， n年过去了， 好多细节我已经忘记了。
第一个问题， 我想当初是为了支持中文等任何编码的密钥才在代码里先把密钥转换为16进制。
第二个问题， 这个得仔细去看一下 des 原理， 老实说为什么这么写我也已经忘了。

**Comment by zyx0609** [comment]
> 不好意思， 这代码还是我n年前学密码学的时候敲的代码， n年过去了， 好多细节我已经忘记了。
> 第一个问题， 我想当初是为了支持中文等任何编码的密钥才在代码里先把密钥转换为16进制。
> 第二个问题， 这个得仔细去看一下 des 原理， 老实说为什么这么写我也已经忘了。

谢谢！
